<?php require '../config/config.php'; require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){
  $id=(int)($_POST['id']??0); $action=$_POST['action']??'';
  if($action==='update'){
    $status=$_POST['status']??'open'; $note=trim($_POST['admin_note']??'');
    if(in_array($status,['open','in_progress','resolved','closed'],true)){$pdo->prepare('UPDATE support_requests SET status=?,admin_note=? WHERE id=?')->execute([$status,$note?:null,$id]);flash('success','Support request updated.');}
  } elseif($action==='delete'){$pdo->prepare('DELETE FROM support_requests WHERE id=?')->execute([$id]);flash('success','Support request deleted.');}
  header('Location: support.php');exit;
}
$rows=$pdo->query('SELECT sr.*,u.name,u.email,u.phone FROM support_requests sr LEFT JOIN users u ON u.id=sr.user_id ORDER BY sr.created_at DESC')->fetchAll();
$title='Support Requests'; require '../includes/header.php'; ?>
<div class="adminnav"><div class="container"><a href="index.php">Dashboard</a><a href="members.php">Members</a><a href="online-users.php">Online Users</a><a href="administrators.php">Administrators</a><a href="reports.php">Reports</a><a href="support.php">Support Requests</a><a href="donations.php">Donations</a><a href="events.php">Events</a><a href="news.php">News</a><a href="messages.php">Messages</a></div></div>
<section class="section"><div class="container"><h1>Support Requests</h1><p class="muted">Only administrators can manage requests. Members can submit requests and view open community requests.</p><div class="tablewrap"><table class="table"><thead><tr><th>Member</th><th>Request</th><th>Category</th><th>Status</th><th>Admin Note</th><th>Action</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="6" class="empty">No support requests.</td></tr><?php endif; ?><?php foreach($rows as $r): ?><tr><td><strong><?=e($r['name']?:'Deleted member')?></strong><br><span class="muted smalltext"><?=e($r['email']??'')?></span></td><td><strong><?=e($r['title'])?></strong><br><?=nl2br(e($r['description']))?></td><td><?=e($r['category'])?></td><td><span class="status <?=e($r['status'])?>"><?=e(str_replace('_',' ',ucfirst($r['status'])))?></span></td><td><?=e($r['admin_note']?:'—')?></td><td><details><summary class="mini-btn">Manage</summary><form method="post" class="reset-form" style="position:relative;top:auto;right:auto;width:260px"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=e($r['id'])?>"><label>Status</label><select name="status"><option value="open" <?=$r['status']==='open'?'selected':''?>>Open</option><option value="in_progress" <?=$r['status']==='in_progress'?'selected':''?>>In progress</option><option value="resolved" <?=$r['status']==='resolved'?'selected':''?>>Resolved</option><option value="closed" <?=$r['status']==='closed'?'selected':''?>>Closed</option></select><label style="margin-top:8px">Admin note</label><textarea name="admin_note" style="width:100%;min-height:80px"><?=e($r['admin_note']??'')?></textarea><button class="mini-btn" type="submit">Save</button></form><form method="post" onsubmit="return confirm('Delete this request?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=e($r['id'])?>"><button class="mini-btn danger" type="submit">Delete</button></form></details></td></tr><?php endforeach; ?></tbody></table></div></div></section><?php require '../includes/footer.php'; ?>
